spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${CLIENT_ID} # EC2 환경변수 설정하기
            clientSecret: ${CLIENT_SECRET}  #EC2 환경변수 설정하기
            scope:
              - email
              - profile

logging.level:
  org.hibernate.SQL: debug

jwt:
  key: g767fytcv76gv6vt6767fgfjnghjftgghf655878fgutyv # EC2 환경변수 설정하기
  access-token-expiration-minutes:  30
  refresh-token-expiration-minutes: 420